### ISSUE TITLE
1.14.4-1.1.5 /spawn crashes dedicated server

### ISSUE THREAD

**Issue by kreezxil** [Maciej916/Ma-Essentials#14]
crash-2019-10-25_20.45.11-server.txt http://paste.ubuntu.com/p/nXqKtjD2yH/

latest.log http://paste.ubuntu.com/p/s7sCGrzwqW/

server crashed when player gave /spawn command

**Comment by Maciej916** [comment]
Try to remove data.json file from ma-essentials catalog on server, probably you have outdated file.

**Comment by kreezxil** [comment]
I wish you had responded sooner. I have went back to Elrol's Server
Utilities to resolve the issue.
