### ISSUE TITLE
default_kits.json resets upon new world load

### ISSUE THREAD

**Issue by Gunzoffire** [Maciej916/Ma-Essentials#16]
**Describe the bug**
So I can't seem to understand how the default_kits.json keeps getting reset, as far as I can understand and write everything out correctly in the file I go make a fresh world and the file gets reset to default removing the things I've added which was leather, string and ender pearls.

**To Reproduce**
1.edit the file, click save, close the file, close npp, load minecraft, load a world, type in /kit ??? its not there??? that is odd I know I saved it, I check the file and it has reset itself.

**Expected behavior**
The "bags" area of the file I linked to be saved and loaded in fine so I could use the kit

**Versions** 1.14.4
- **Ma Essentials**: 1.1.5
- **Forge**: 28.1.61

**Additional context**
Links to crash reports, logs, images, videos, or related issues, if appropriate.
https://pastebin.com/A0AQGerh

**Comment by Maciej916** [comment]
Thank you for reporting this issue. Ill fix this bug in next version.

**Comment by Maciej916** [comment]
Fixed in [v1.1.6](https://www.curseforge.com/minecraft/mc-mods/maessentials/files/2817849)
