### ISSUE TITLE
[1.14.4-1.1.8] Transdimensional Travel crashes dedicated server

### ISSUE THREAD

**Issue by kreezxil** [Maciej916/Ma-Essentials#17]
**Describe the bug**
teleporting to and from the end causes a dedicated server to crash

**To Reproduce**
1. go to the end
1. set a home there
1. type /spawn
1. that's when my server crashed

**Expected behavior**
not crash the server

**Versions**
- **Ma Essentials**: 1.14.4-1.1.8
- **Forge**: 28.1.79

**Additional context**
crash report:
http://paste.ubuntu.com/p/QPWrPsZdxn/

fml server latest:
http://paste.ubuntu.com/p/mxV3RnzbPt/

**Comment by Maciej916** [comment]
I tried to reproduce your issue but it's working just fine for me. Can you show me your **world/ma-essentials/data.json**

**Comment by kreezxil** [comment]
You still have that file be saved to <server root>/ma-essentials/ which is outside the world/ folder.

http://paste.ubuntu.com/p/3jhZb2NgYH/

going to wipe that data file now

**Comment by kreezxil** [comment]
oops hit wrong button

**Comment by Maciej916** [comment]
Change "spawnPoint" to "spawn" and it should work. You have outdated file and that's why it's not working.

**Comment by kreezxil** [comment]
for some reason deleting the ma-essentials folder resolves the issue but then the lang file screws up

![image](https://user-images.githubusercontent.com/3880072/68090981-f9de4900-fe3f-11e9-815d-3ba834292a6c.png)

ok, thanks for the fix suggestion

**Comment by Maciej916** [comment]
Mod needs to be installed on server and client

**Comment by kreezxil** [comment]
yes, i have it on both sides. changing that one data entry on the server
appears to have resolved the issue. I tested it. you can close this.
