### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by BedrockLegends** [Maciej916/Ma-Essentials#18]
## What should be added or changed?
/Ban, Bans a player. This is a great command for anyone who use this on server side.
/Broadcast, Allows a server admin or OP to send a message to the entire server chat in-game.
/Checkban, This allows server admins or Ops to check a ban or temp ban status of a player
/checkmute or /checkmuted, to allow server admins or Ops to check if someones muted
/hat, allows a player to put said item in their hand on their head as a Helmet.
/ignore, Allows a said player or server op the ability to ignore incoming chat messages from a player they dont want to deal with
/Invcheck, Allows server Ops or admins to check players inventory
/rules, Allows Modpack creators or server owners ship their modpack or run their server with a set rule list from a Json file
/trash, Opens a gui or inventory that allows you to throw away items.

Away to see if any of the said commands above can be added in some way
- (Description)

## Why should this be done?
Would help Modpack creators or server owners that use this mod

Away for people who download this to have commands to help them out
- (Description)

**Comment by Maciej916** [comment]
Thank you for your suggestions. Currently i need to redo some internal code before i'll implement more functions but most of your suggestions will be added in the future.

**Comment by Maciej916** [comment]
Added **/broadcast** command in v1.2.1
Added **/trash** command in v1.2.3
Chat rules are vailable in my other plugin [Ma Chat](https://www.curseforge.com/minecraft/mc-mods/ma-chat)

**Comment by Maciej916** [comment]
Added  **/tempban <targetPlayer> <time> <reaon>** command in v1.2.4
Added **/check <bans,mutes>** command in v1.2.5
