### ISSUE TITLE
maessentials /spawn crashes server

### ISSUE THREAD

**Issue by Tarlin83** [Maciej916/Ma-Essentials#19]
**Describe the bug**

As stated above, doing /spawn will cause a server tick issue and crash the server

**To Reproduce**
1. load the server
2. type /spawn
3. crash the server

**Expected behavior**
Get teleported to spawn when using /spawn

**Versions**
- **Ma Essentials**: 1.2.3
- **Forge**: 28.1.87

**Additional context**
Crash report:
https://paste.ubuntu.com/p/MXz8vfCP4Z/

This is being used in multiple modpacks and servers run by Kreezxil to include The Seilican Experience, Minecolonies Getting Started, World of Dragons and World of Dragons - New Age.
This is only crashing the server on The Seilican Experience and Minecolonies Getting Started. Works on the other servers. All the same version.

crosslink:
https://github.com/kreezxil/the-seilican-experience/issues/14
https://github.com/kreezxil/minecolonies-getting-started/issues/21

**Comment by Maciej916** [comment]
Did you updated from older version or it was new installation?

**Comment by Tarlin83** [comment]
Updated from the previous version. The mod is on multiple servers, so to do a complete uninstall and reinstall would have caused conflicts with players losing homes and having to redo things after already having them established.

**Comment by Maciej916** [comment]
If you update from old version there is high chance you have outdated file with spawn coordinates. I'll make patch to auto update this file in next version but for now you can fix this by using /setspawn or deleteing **/ma-essentials/data.json** and restart server.
