### ISSUE TITLE
[BUG] Unable to /setwarp and /delwarp without cheating.

### ISSUE THREAD

**Issue by untidymaster** [Maciej916/Ma-Essentials#2]
Mod version: 1.0.5
Forge version: 28.1.33
Minecraft version: 1.14.4

**Comment by Maciej916** [comment]
Commands /setwarp and /delwarp are available ony for ops it's not bug.Warps are public teleports available for any player and only server operator can set and delete them.

**Comment by untidymaster** [comment]
Oops, my apologies.

**Comment by Maciej916** [comment]
No problem
