### ISSUE TITLE
Doing /sethome <alreadycreatedhome> does not update that home to new location

### ISSUE THREAD

**Issue by AzureZhen** [Maciej916/Ma-Essentials#20]
When a player first sets a home using /sethome, it creates a default home. When a player moves and tries to do /sethome home, it's not updating the default home location, instead teleporting to the new updated home location.

1. Create a home using /sethome
2. Move to another location and do /sethome home
3. Do /home home 
4. You are moved to the old location instead of the new location.

**Expected behavior**
What is expected is that using the /sethome <alreadycreatedhome> command updates the home location to the new one. 

**Versions**
- **Ma Essentials**: 1.2.4
- **Forge**: 1.14.4

**Comment by Maciej916** [comment]
Fixed in [v1.2.5](https://www.curseforge.com/minecraft/mc-mods/maessentials/files/2830461)
