### ISSUE TITLE
Not showing correct messages in chat

### ISSUE THREAD

**Issue by monokin1114** [Maciej916/Ma-Essentials#21]
**Describe the bug**
Using any command that has a chat message doesn't show what would be expected.

**To Reproduce**
Type any command that produces a chat message.

**Expected behavior**
Show expected message IE-Teleporting to spawn please wait. Instead of spawn.maessentials.success.wait. Among others

**Versions**
- **Ma Essentials**: 1.2.4
- **Forge**: 28.1.88
![Screenshot_4](https://user-images.githubusercontent.com/47362628/69288076-7bff9900-0bc6-11ea-9e81-3c909f0ac4f4.png)

**Comment by Maciej916** [comment]
This is not server side mod, you need to install it on client side also in order to mod work properly.

**Comment by monokin1114** [comment]
May I suggest a config option to remove it sending things in chat then. Since it clearly does work as a server side only mod. Minus the chat messages.

**Comment by Maciej916** [comment]
Yes it works if mod is only installed on server but client is required to provide proper translations. This could be done in resourcepack but its easier to just install mod on client.
