### ISSUE TITLE
Regarding kits

### ISSUE THREAD

**Issue by lastedito** [Maciej916/Ma-Essentials#26]
## What should be added or changed?

-  Would be great to add comands to customize kits in game, because I'm hosting my server on Aternos and it doesn't let you access further files so I cant reach where we edit kits. So I'm blocked with 2 kits only.

## Why should this be done?

- I don't think Aternos is the only server hosting platform that does it this way, and it will help a lot  of people. Plus I think, kits is an indispensible thing in servers so I would gladly appreciate it being implemented !

**Comment by lastedito** [comment]
Or please move the default-kits file in the config folder please ^^ Thats the only folder we have access

**Comment by Maciej916** [comment]
I'll add kit creator in new versions but now I'm really busy and I don't have time to make it.

**Comment by lastedito** [comment]
> I'll add kit creator in new versions but now I'm really busy and I don't have time to make it.

Alright thanks!
