### ISSUE TITLE
/rndtp and nether roof.

### ISSUE THREAD

**Issue by LezChap** [Maciej916/Ma-Essentials#27]
**Describe the bug**
It appears that /rndtp allows teleportation to the nether roof.  This is probably not an intended mechanic.

**Versions**
- **Ma Essentials**: 1.14.4-1.2.8
- **Forge**: 28.1.109

**Comment by Maciej916** [comment]
Fixed in[ v1.2.10](https://www.curseforge.com/minecraft/mc-mods/maessentials/files/2859552)
