### ISSUE TITLE
Invsee GUI immediately closes

### ISSUE THREAD

**Issue by LezChap** [Maciej916/Ma-Essentials#28]
**Describe the bug**
Trying to use the /invsee on a server.  I see a gray GUI screen flash open for a split second most of the time, and then immediately close before I can make out any details.  No errors or anything else show up in the console logs (both server and client logs).

**Versions**
- **Ma Essentials**: 1.2.9
- **Forge**: 28.1.109

**Comment by Maciej916** [comment]
I'll check that

**Comment by ApexTheElite** [comment]
This is still happening on 1.15.2

Forge version: 1.15.2-31.1.1
Ma-Essentials Version: 3.0.0

**Comment by winnieduhpoooh** [comment]
I figured out today you can only /invsee in front of the player. It's not a bug.

**Comment by AngelicBeatz** [comment]
so it is like an checking a chest if you are to far you can't see it ok.

**Comment by Maciej916** [comment]
It's a bug and it will be fixed in future update, because it should work always not only if you are close enough to player.
