### ISSUE TITLE
Warmup on back

### ISSUE THREAD

**Issue by Yamza** [Maciej916/Ma-Essentials#29]
## What should be added or changed?
I would like /back to have a configurable warm up period, so that when a player dies they must wait a set amount of time before /back will take them to their death point.

## Why should this be done?
This will allow for an alternative way to get back to the grave, while not being able to zerg deaths. I would prefer this over the cooldown because I also intend to have the Corails Tombstone mechanics available for people who either invest into enchanting their key or stocking up on pearls.

Example: Player dies, they get their grave key. They can choose to enchant the key immediately or wait for /back to become available. This is intended to be a contingency for players who forget to do /sethome when they go off exploring and die unintentionally.

**Comment by Maciej916** [comment]
Added in[ v1.2.10](https://www.curseforge.com/minecraft/mc-mods/maessentials/files/2859552)
