### ISSUE TITLE
[1.14.4] /rndtp command is only available to Operators.

### ISSUE THREAD

**Issue by Gbergz** [Maciej916/Ma-Essentials#31]
**Describe the bug**
*/rndtp command is only available to Operators.*

**EDIT**
Command is enabled in the config. Though only works for Operators as stated above.

**To Reproduce**
1. Try to use /rndtp
2. Says 'Unknown Command'
3. See image here: [https://i.imgur.com/mNnH9f8.png](https://i.imgur.com/mNnH9f8.png)
4. Profit.

**Expected behavior**
That non-Operators can use the command.

**Versions**
- **Minecraft**: 1.14.4
- **Ma Essentials**: 1.2.10
- **Forge**: 28.1.107

**Additional context**
*This issue wasn't happening on the earlier versions.*
Or am I missing something? Was there a config change?.
~ Gbergz

**Comment by Maciej916** [comment]
My mistake, fixed in [v1.2.11](https://www.curseforge.com/minecraft/mc-mods/maessentials/files/2863732)
