### ISSUE TITLE
[1.14.4] "Exception in server tick loop" - Crash

### ISSUE THREAD

**Issue by Gbergz** [Maciej916/Ma-Essentials#32]
**Describe the bug**
Server crashes randomly, not entirely sure how to reproduce it or describe it better than that.
As we did not do anything special to trigger it.

**Expected behavior**
Server not crashing randomly.

**Versions**
- **Ma Essentials**: 1.2.11
- **Forge**: 28.1.107

**Additional context**
Crash-report: https://gist.github.com/Gbergz/59a19e4ce569aabcec8191149d2ec5c1

Any ideas?

**Comment by Maciej916** [comment]
Possibly fixed for 1.15.2 in [v3.0.1](https://www.curseforge.com/minecraft/mc-mods/maessentials/files/2893503)
