### ISSUE TITLE
1.15.2 rndtp cooldown bug

### ISSUE THREAD

**Issue by Yamza** [Maciej916/Ma-Essentials#33]
**Describe the bug**
When using rndtp and you move, the cooldown begins even though you didn't teleport.

**To Reproduce**
1. Start a rndtp command
2. Move to cancel it
3. Command will now be on cooldown

**Expected behavior**
Cooldown shouldnt trigger until successful teleport is completed.

**Versions**
- **Ma Essentials**: Ma-Essentials-1.15.2-3.0.0.jar
- **Forge**: forge-31.1.12

**Comment by Maciej916** [comment]
Fixed in [v3.0.1](https://www.curseforge.com/minecraft/mc-mods/maessentials/files/2893503)
