### ISSUE TITLE
1.15.2 rndtp command cancel

### ISSUE THREAD

**Issue by Yamza** [Maciej916/Ma-Essentials#34]
**Describe the bug**
If you move before putting in the command, it seems the client doesn't register you stopping until later. A second or two. Simply waiting a short time before doing /home was able to let me teleport
I say client, because this happens in single player too
If you jump, and while in the air, type it, then as you land, it wont work, it'll imply you moved. Even if you're still.
Or if you move, and quickly type it, it'll also do that, even if still

**Expected behavior**
Might be good to have a 1-2 second grace period so that stopping movement doesn't cancel the command. 

**Versions**
Ma Essentials: Ma-Essentials-1.15.2-3.0.0.jar
Forge: forge-31.1.12

**Comment by Maciej916** [comment]
Yeah i know that restriction to don't move while teleport is verry restricted alot, I'll probably work to make it a bit less restrictive and allow small moves. About random teleport I can not reproduce this.
