### ISSUE TITLE
Can't use any commends

### ISSUE THREAD

**Issue by ReQuu** [Maciej916/Ma-Essentials#35]
**Describe the bug**
My friends on server cannot use any commends with this mods but I can. When they type somethin in console they get this message: "Unknown Command"
I've tried to reinstall mod but it don't help anyway.
I've cleared all logs - same.
Can you help me? Maybe some mods are broken but i have the same list and it works perfectly on my Minecraft.

**Versions**
- **Ma Essentials**: v1.2.11
- **Forge**: 1.14.4 28.2.0

**Additional context**
List of installed mods and friend issue:
![explorer_UeOi6jkHRW](https://user-images.githubusercontent.com/61250383/74870319-d3460e80-5359-11ea-9317-37db7ce81b41.png)
![explorer_Z7B2Kcwa7v](https://user-images.githubusercontent.com/61250383/74870394-ed7fec80-5359-11ea-92b9-20f7fd0f05fb.png)
![explorer_VvBsN9jE3k](https://user-images.githubusercontent.com/61250383/74870401-f1137380-5359-11ea-99e5-af2dd783a4bd.png)
![Discord_hDQfAYw8wD](https://user-images.githubusercontent.com/61250383/74870977-f6bd8900-535a-11ea-8227-ed83a0ea5d17.png)

**Comment by Maciej916** [comment]
Check console for any errors
