### ISSUE TITLE
[1.15.2] client crashes

### ISSUE THREAD

**Issue by EnterFor** [Maciej916/Ma-Essentials#38]
**Describe the bug**
Don't know how it happened, but have crash reports
When I restarted the game, it didn't happen
Game environment: LAN, online with friends

**Versions**
- **Ma Essentials**:3.0.1
- **Forge**: 31.1.18

**Additional context**
[crash-2020-03-06_22.05.31-server.txt](https://github.com/Maciej916/Ma-Essentials/files/4299258/crash-2020-03-06_22.05.31-server.txt)

**Comment by Maciej916** [comment]
Fixed in 1.15.2 v3.0.2
