### ISSUE TITLE
Crash on AFK-kick

### ISSUE THREAD

**Issue by codegavran** [Maciej916/Ma-Essentials#39]
Server crashes when a player is afk kicked.

1. Enable AFK kick in config (ours was set to 600)
2. Become flagged ask AFK (via waiting or /afk)
3. Get kicked
4. Server crashes

Crash log: https://pastebin.com/BDrduvXx

note: exception is thrown after player is kicked, player in question displays the kick screen in their client not the server crash

**Comment by Maciej916** [comment]
Fixed in 1.15.2 v3.0.2
