### ISSUE TITLE
[1.15.2] Crash on teleport

### ISSUE THREAD

**Issue by Yamza** [Maciej916/Ma-Essentials#41]
**Describe the bug**
Occasional crash when players use teleport commands.

**To Reproduce**
Per the player in question: "I ported to home and then to spawn, was it it?"

**Expected behavior**
Not crash during teleport.

**Versions**
- **Ma Essentials**: ma-essentials@1.15.2-3.0.1
- **Forge**: 31.1.18

**Additional context**
Crash Report: https://pastebin.com/st73cYq1
Log: https://gist.github.com/Yamza/3d24890d84559146f6cbebc69c7cf63e

**Comment by Maciej916** [comment]
Fixed in 1.15.2 v3.0.2
