### ISSUE TITLE
Issues with timed bans.

### ISSUE THREAD

**Issue by MilesTFox** [Maciej916/Ma-Essentials#42]
![2020-03-09_00 45 42](https://user-images.githubusercontent.com/21246610/76262653-54931180-6233-11ea-9e9d-b99edabfbd7b.png)
![2020-03-09_00 03 42](https://user-images.githubusercontent.com/21246610/76262657-5957c580-6233-11ea-941b-d4f6392279c9.png)

**Comment by MilesTFox** [comment]
'secoonds(s)'

**Comment by MilesTFox** [comment]
Additional information: Admin removed the playerdata file for me on server, attempting to remove the ban, now instead of the 'banned for '.', internal server error.

**Comment by MilesTFox** [comment]
https://pastebin.com/tM2DjHP2

[tM2DjHP2.txt](https://github.com/Maciej916/Ma-Essentials/files/4319611/tM2DjHP2.txt)

Server log from recent connect attempts

**Comment by Maciej916** [comment]
> Additional information: Admin removed the playerdata file for me on server, attempting to remove the ban, now instead of the 'banned for '.', internal server error.

1. I'll fix typo in next update.
2. To remove your ban he needs to edit or delete file from `/ma-essentials/players/YOUR-UUID`
