### ISSUE TITLE
json file not recognized for server members

### ISSUE THREAD

**Issue by BrendGroen** [Maciej916/Ma-Essentials#43]
Hello, 

I have recently installed this mod on my 1.15.2 forge server. 
![image](https://user-images.githubusercontent.com/39187637/76520686-af12b480-6463-11ea-835c-04aa089bc89d.png)
At this image you see my config file. The top file is a json file that should translate some of them weird codes and the bottom one is the mod config. For me, this json file works very well but none of my server members see this text. How can I fix this?

Another bug is that when I type /invsee <player> it appears and immediately disappears.

Any help would be really appreciated!!

**Comment by Maciej916** [comment]
Why don't you install mod on client side to enable translations by client instead you trying to solve it different way. Config for single player is the same as on multiplayer so it should work on server also if you copy it correctly. For invsee bug i know about that and ill try to fix this in future versions.

**Comment by TheFlash787** [comment]
@Maciej916 This is a server mod, to provide utilities for a server. Why should this *need* to be installed clientside too, in order for people to see the messages that you send from the plugin:
![image](https://user-images.githubusercontent.com/25883284/78301241-b5f78900-7530-11ea-87b8-0c7508a4513b.png)

It makes no sense for this plugin to be necessary on the client, when it's a server mod. Most clients will not come with this mod shipped by default, and will therefore cause problems.

**Comment by Maciej916** [comment]
1. It't not server mod it's single player and multiplayer mod.
2. Client need to have it installed to support translations and languages, that was since beginning and i'm not planning to change that maybe in future ill make that option.
