### ISSUE TITLE
Version checking is not matching correctly

### ISSUE THREAD

**Issue by DesertDwarf** [Maciej916/Ma-Essentials#44]
Description:

I see this in my console every time I restart the server. It doesn't think that 1.15.2-3.0.2 is the same as 3.0.2.

01.04 10:46:30 [Server] Forge Version Check/INFO [ne.mi.fm.VersionChecker/]: [ma-essentials] Starting version check at https://raw.githubusercontent.com/Maciej916/Ma-Essentials/1.15.2/update.json
01.04 10:46:30 [Server] Forge Version Check/INFO [ne.mi.fm.VersionChecker/]: [ma-essentials] Found status: OUTDATED Current: 1.15.2-3.0.2 Target: 3.0.2

**Comment by Maciej916** [comment]
Fixed
