### ISSUE TITLE
Xp disapear when switch to nether

### ISSUE THREAD

**Issue by MrGuitou** [Maciej916/Ma-Essentials#47]
**Describe the bug**
Xp disapear from XP bar when go to another dimension with /home function

**To Reproduce**
1. /sethomes in different dimension
2. use /home to teleport form a dimension to another
3. See your XP bar empty and level disapeared

**Versions**
- **Ma Essentials**: 3.0.2
- **Forge**: 31.1.30++ (tested on 3 versions, 30, 34 and 43 - same thing for all)

**Additional context**

It's seems to be just a graphical issues when ma-essential is alone, but cause a real loose if other mods adding more dimensions are installed

I had not tested teleport to/from ender yet

_When ma-essential is alone:_
Minning an ore which give XP make things come back to normal
Using a portal to come back in starting dimension make things come back to normal

_When other dimentionals mods are present:_
XP definitely loosed.

No debug log visible neither on client nor server from this issue.

**Comment by Troubl96** [comment]
Teleport back to the dimension using the portal and then back through the portal to home. XP is not lost just not carried over the home/back command

**Comment by Maciej916** [comment]
As far i know it's only visual bug but i'll try to do something about it.
