### ISSUE TITLE
Add Config Option 

### ISSUE THREAD

**Issue by SilverKytten** [Maciej916/Ma-Essentials#51]
If it's possible, could you add a config option to disable the "stay still" requirements, when teleporting? 

I don't use the delay option, and my players have reported sending a tphere request only for it to be cancelled when the other player accepts, because the sending was moving.
![image](https://user-images.githubusercontent.com/2188185/82509094-8c88c180-9acc-11ea-8e4b-fbee3a3ca033.png)

**Comment by Maciej916** [comment]
Just change tpa delay to 0 in config to diable "stay still" before teleport.

**Comment by SilverKytten** [comment]
Sorry, I didn't see the notification that you had replied until just now. 
That is how I have it set, it does not disable the need to stand still.
![Screenshot_20200607-115257_Termius](https://user-images.githubusercontent.com/2188185/83974846-dbe53500-a8b5-11ea-99dd-9fa31be799b1.jpg)

**Comment by Maciej916** [comment]
I'll check and that thanks for info
