### ISSUE TITLE
Server Side only request

### ISSUE THREAD

**Issue by AngelicBeatz** [Maciej916/Ma-Essentials#52]
## What should be added or changed?

I would love this to be server sided only or at least be an option.
- (Description)

## Why should this be done?

This would add to the download factor because the reason I can't commit yet is because I want to use a stock FTB mod pack but I cant just have them add it just for me or have players do this kind of stuff because what else would they drag into there mod folder if they knew how to.
- (Description)

**Comment by Maciej916** [comment]
Sorry but I don't plan to release server side only version of this mod.
