### ISSUE TITLE
[1.15.2] Updating from 3.0.3 to 3.1.0 change folder and wipe inventory

### ISSUE THREAD

**Issue by didis54** [Maciej916/Ma-Essentials#54]
**Describe the bug**
After updating to 3.1.0 the folder which contain all data from home, warp etc has changed from "ma-essentials" to "maessentials"
This has caused my inventory to get wiped out because i was considered as a new player. (and re-given the starter kit)

**Expected behavior**
When updating to 3.1.0 content of the old folder should be automatically moved to the new one. Or at least prevent people to do it in the changelog.

**Versions**
- **Ma Essentials**: 3.1.0
- **Forge**: 32.2.9

**Additional context**
I've been able to resolve this bug myself by moving the old folder content, but this could be nice to put it somewhere to avoid people having too much trouble.

**Comment by Maciej916** [comment]
Fixed in [v3.1.1](https://www.curseforge.com/minecraft/mc-mods/maessentials/files/2979463)
