### ISSUE TITLE
[1.15.2] /Fly Persistence

### ISSUE THREAD

**Issue by GatekeeperTDS** [Maciej916/Ma-Essentials#55]
It would be great if /fly status could be retained between logins. If a player has /fly enabled, it should be enabled until they turn it off manually.

Could this possibly be stored in the data files along with the player's homes and other data?

Thank you.

**Comment by Maciej916** [comment]
It's good idea also it can be applied for /god, i'll add this in next update.

**Comment by Maciej916** [comment]
Added in [1.16.1 v3.2.2](https://www.curseforge.com/minecraft/mc-mods/maessentials/files/2997088)

**Comment by GatekeeperTDS** [comment]
Are you going to add these updates to 1.15 also?
