### ISSUE TITLE
[1.15.2] Case Sensitivity

### ISSUE THREAD

**Issue by GatekeeperTDS** [Maciej916/Ma-Essentials#57]
Hi - Not exactly a bug, but not an enhancement, so I wasn't sure how to classify this one.

It would be awesome if the commands weren't case sensitive, sometimes a command fails if caps lock is on or if any part of the command is capitalized at all.

![image](https://user-images.githubusercontent.com/66881994/86158306-998ace80-bad6-11ea-837a-cd6eb1c1d9dc.png)

Thank you.

**Comment by Maciej916** [comment]
I don't know if it's possible in forge. I'll check that.
