### ISSUE TITLE
Ma-essentials i cant using 1.16.1

### ISSUE THREAD

**Issue by MrScautHD** [Maciej916/Ma-Essentials#59]
On my modpack is Ma-essentials and Ma-essentials is not working
notfing command
(german) Es wäre so wie wen dieser mod nie Exestiren würde!

**Expected behavior**

**Versions**
- **Ma Essentials**:the newest
- **Forge**: 1.16.1

Lastlog of my server
[latest.log](https://github.com/Maciej916/Ma-Essentials/files/4875184/latest.log)

**Comment by Maciej916** [comment]
Logs you provided does not explain anything, there is no error regarding to Ma-Essentials mod.

**Comment by MrScautHD** [comment]
i dont can use command or other.

**Comment by Maciej916** [comment]
Do you have it installed on both client and server? If not it's probably your issue.
