### ISSUE TITLE
/kits

### ISSUE THREAD

**Issue by Peterp108** [Maciej916/Ma-Essentials#61]
I have a problem with /kits on my serwer.
I opened a file "default_kits" and deleted kits "enderchest" and "tools", but they are still on server.
How to delete them?

**Comment by Maciej916** [comment]
File default_kits.json does nothing on server it's only used for single player worlds. To edit kits on server edit file kits.json in maessentials catalog.

**Comment by Peterp108** [comment]
Where is this catalog?
Because I can't find it :/

**Comment by Peterp108** [comment]
The problem is that in file ma-essencial I have only "default-kits". There is no file "kits.json"

**Comment by Peterp108** [comment]
I need to create this file myself?

**Comment by Peterp108** [comment]
I found it in different way, thanks!
