### ISSUE TITLE
"/god" mode does not exist or returns an error

### ISSUE THREAD

**Issue by VallenFrostweaver** [Maciej916/Ma-Essentials#62]
**Describe the bug**
Using the `/god` command as admin returns `Invalid gamemode` or changes nothing of note.

**To Reproduce**
1. Be admin
2. Type in chat either `/god` or `/god <player name>`

**Expected behavior**
Any change that would make the player invulnerable at least.

**Versions**
- **Minecraft**: 1.16.1
- **Ma Essentials**: 1.16.1-3.2.2
- **Forge**: 32.0.47

**Additional context**
If in Creative Mode when executing the command the response says `Invalid gamemode`.
If in Survival Mode when executing the command there is no response.
In either case, nothing changes.

**Comment by Maciej916** [comment]
Fixed in [v3.2.4](https://www.curseforge.com/minecraft/mc-mods/maessentials/files/3022628)
