### ISSUE TITLE
Claim command

### ISSUE THREAD

**Issue by nivowski** [Maciej916/Ma-Essentials#65]
A fully implemented claim command in which you can claim land, add/remove player from interacting with the claim such as griefing, promote/demote members from the land claimed, name the claimed land

**Comment by SDUBZ** [comment]
I would love this feature to be implemented since there seems to be really a lack of this type of mod for no good reason

**Comment by Maciej916** [comment]
I'll consider to make it as a separate mod because it shouldn't be hard.
