### ISSUE TITLE
Ma essentials mod causing server to crash

### ISSUE THREAD

**Issue by NR472** [Maciej916/Ma-Essentials#66]
Error: Exception caught during a firing event 

**Versions**
- **Ma Essentials**: 3.2.2
- **Forge**: 32.0.67

Log:
https://mclo.gs/6VcL1Dc

**Comment by Maciej916** [comment]
Please downgrade forge to 32.0.66 or wait for mod update because in that version they changed how commands are registering.

**Comment by NR472** [comment]
Thank you, do you know approximately when a mod update might be released?
