### ISSUE TITLE
Fly command not working

### ISSUE THREAD

**Issue by NR472** [Maciej916/Ma-Essentials#67]
**Describe the bug**
Nothing happens when I type in the /fly command.

**Versions**
- **Ma Essentials**: 3.2.3
- **Forge**: 32.0.69

**Additional context**
https://mclo.gs/kEa5HvS

**Comment by KoopaEnder** [comment]
Same here

**Comment by Maciej916** [comment]
I'll fix the issue as soon i find some free time.

**Comment by looneym** [comment]
Hey @Maciej916  👋  Thanks a lot for the mod. I would be interested in trying to fix this, if you could point me in the direction of where to begin? I use Ruby in my day job but I have some Java experience

**Comment by Maciej916** [comment]
Fixed in [v3.2.4](https://www.curseforge.com/minecraft/mc-mods/maessentials/files/3022628)
