### ISSUE TITLE
Trying to add item with lots of nbt to kit

### ISSUE THREAD

**Issue by tobi-polar** [Maciej916/Ma-Essentials#68]
This isn't exactly a bug but I'm trying to figure out how to add an akashic tome which is a book that holds other guide books, to a kit. I used craft tweakers /ct hand command and copied the item and it's nbt but that hasn't worked for me and I don't really understand json/nbt very well. Would it be possible to add a command that takes whatever a person is holding in their hand with its nbt and adds it to a kit? I saw you mention you're adding a gui to the 1.16 version and suggested that people use the gui on 1.16 and than use the generated file on 1.15 but this tome item isn't available on 1.16 😅

{
  "kits": {
    "tome": {
      "duration": 3600,
      "items": [
        {
          "name": "akashictome:tome",
          "quantity": 1,
          "nbt": ".withTag({"akashictome:is_morphing": 1, "akashictome:data": {powah: {id: "powah:book" as string, Count: 1}, engineerstools: {id: "patchouli:guide_book" as string, Count: 1, tag: {"patchouli:book": "engineerstools:engineerstools_manual" as string}}, planttech2: {id: "planttech2:guide_overview" as string, Count: 1, tag: {Damage: 0}}, golems: {id: "golems:info_book" as string, Count: 1}, immersiveengineering: {id: "immersiveengineering:manual" as string, Count: 1, tag: {"akashictome:displayName": "{\"translate\":\"item.immersiveengineering.manual\"}" as string, "akashictome:is_morphing": 1, display: {Name: "{\"translate\":\"akashictome.sudo_name\",\"with\":[{\"color\":\"green\",\"translate\":\"item.immersiveengineering.manual\"}]}" as string}}}, rftoolsbase: {id: "rftoolsbase:manual" as string, Count: 1, tag: {"akashictome:displayName": "{\"translate\":\"item.rftoolsbase.manual\"}" as string, "akashictome:is_morphing": 1, display: {Name: "{\"translate\":\"akashictome.sudo_name\",\"with\":[{\"color\":\"green\",\"translate\":\"item.rftoolsbase.manual\"}]}" as string}}}, woot: {id: "patchouli:guide_book" as string, Count: 1, tag: {"akashictome:displayName": "{\"translate\":\"item.woot.wootguide.name\"}" as string, "patchouli:book": "woot:wootguide" as string, "akashictome:is_morphing": 1, display: {Name: "{\"translate\":\"akashictome.sudo_name\",\"with\":[{\"color\":\"green\",\"translate\":\"item.woot.wootguide.name\"}]}" as string}}}, valkyrielib: {id: "valkyrielib:guide" as string, Count: 1, tag: {"akashictome:displayName": "{\"translate\":\"item.valkyrielib.guide\"}" as string, "akashictome:is_morphing": 1, display: {Name: "{\"translate\":\"akashictome.sudo_name\",\"with\":[{\"color\":\"green\",\"translate\":\"item.valkyrielib.guide\"}]}" as string}}}, engineersdecor: {id: "patchouli:guide_book" as string, Count: 1, tag: {"patchouli:book": "engineersdecor:engineersdecor_manual" as string}}, securitycraft: {id: "securitycraft:sc_manual" as string, Count: 1, tag: {"akashictome:displayName": "{\"translate\":\"item.securitycraft.sc_manual\"}" as string, pages: [], author: "Geforce" as string, "akashictome:is_morphing": 1, display: {Name: "{\"translate\":\"akashictome.sudo_name\",\"with\":[{\"color\":\"green\",\"translate\":\"item.securitycraft.sc_manual\"}]}" as string}, title: "SecurityCraft" as string}}}})"
        }
        
      ]
    }
}

**Comment by Maciej916** [comment]
Try to use some JSON Parser online to check if your json is correct, also JSON Stringify might help you.

**Comment by tobi-polar** [comment]
I used this tool to stringify the json: https://onlinejsontools.com/stringify-json
and this tool to validate it: https://jsonlint.com/?code=

Still can't get the kit to work in game.

**Comment by tobi-polar** [comment]
Here's my default kits (changed to .txt to upload to github)
[default_kits.txt](https://github.com/Maciej916/Ma-Essentials/files/5023026/default_kits.txt)
