### ISSUE TITLE
more of a question

### ISSUE THREAD

**Issue by MasterSloth1** [Maciej916/Ma-Essentials#72]
**Describe the bug**
is there a character limit for the nbt tag that you can define inside the default_kits.json?

**To Reproduce**
1. Go to 'defualt_kits.json'
2. edit "nbt": "" line to have roughly 500 characters
3. load game up to find it fail

**Expected behavior**
the nbt tag to load any amount of characters my current tag im trying can be ran perfectly inside a command block ingame

**Versions**
- **Ma Essentials**: 1.15.2-3.1.1
- **Forge**: 31.2.36

**Additional context**
ERROR THAT APPEARS IN CONSOLE
[Server thread/ERROR] [co.ma.ma.co.ut.LogUtils/]: maessentials com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 9 column 150 path $.kits..items[0].nbt

CODE IM RUNNING @ LINE 9
"nbt": "{Damage:0,GEAR_ITEM_DATA:{requirements:{},timesLeveledUp:0,level:1,isUnique:1b,isNotFromMyMod:0b,ided:1b,uniqueStats:{uniqueGUID:\\\"thunder_ele_saber0\\\",percents:{0:164,1:149,2:187,3:156,size:10,4:159,5:122,6:192,7:178,8:137,9:163}},primaryStats:{Mods:{0:{baseModName:\\\"low_attack_thunder_damage_flat\\\",percent:66},size:1}},uniqueGUID:\\\"thunder_ele_saber0\\\",Rarity:-1,secondaryStats-:1b,rightClickSpell:\\\"\\\",isSalvagable:1b,instability:0,runes-:1b,chaosStats-:1b,prefix-:1b,suffix-:1b,gearTypeName:\\\"sword\",set-:1b}}"

ORIGINAL CODE FOR LINE 9 THAT WORKS IN A COMMAND BLOCK
{Damage:0,GEAR_ITEM_DATA:{requirements:{},timesLeveledUp:0,level:1,isUnique:1b,isNotFromMyMod:0b,ided:1b,uniqueStats:{uniqueGUID:"thunder_ele_saber0",percents:{0:164,1:149,2:187,3:156,size:10,4:159,5:122,6:192,7:178,8:137,9:163}},primaryStats:{Mods:{0:{baseModName:"low_attack_thunder_damage_flat",percent:66},size:1}},uniqueGUID:"thunder_ele_saber0",Rarity:-1,secondaryStats-:1b,rightClickSpell:"",isSalvagable:1b,instability:0,runes-:1b,chaosStats-:1b,prefix-:1b,suffix-:1b,gearTypeName:"sword",set-:1b}}

**Additional Additional context**
that code above was generated using https://www.freeformatter.com/json-escape.html i seen in the default_kits.json file you have to escape the double quote marks i wasnt sure if it was just the quotes or all

**Comment by Maciej916** [comment]
Im planning to add kit creation gui that will help to create new kits and help with your issue.
