### ISSUE TITLE
Sethome set to 50 but can only assign 1 in game

### ISSUE THREAD

**Issue by Goredoth** [Maciej916/Ma-Essentials#84]
I have the server and client config files set to 50 homes limit but in game it will only allow 1 home to be set, multiple warps seems to work but the homes don't. 
Not sure why this is happening I have tried doing full installs of server and client and then fixing the config file but still the same issue.

**Comment by Goredoth** [comment]
v 1.16.3
forge 34.1.23

**Comment by Goredoth** [comment]
I have fixed the issue all good i overlooked a config sorry for the trouble

**Comment by Thirstums** [comment]
would you mind telling me what you overlooked? because I have the same problem atm

**Comment by Goredoth** [comment]
I was modifying the client config instead of the server config and for that reason it wasn't setting the limit

**Comment by Thirstums** [comment]
> I was modifying the client config instead of the server config and for that reason it wasn't setting the limit

alright, thank you for the quick response! appreciate it :D. Take care!
