### ISSUE TITLE
Unable to run 1.18 version on my server

### ISSUE THREAD

**Issue by outsore** [Maciej916/Ma-Essentials#92]
Mod File: maessentials-1.18-3.7.0.jar
	Failure message: MaEssentials (maessentials) encountered an error during the common_setup event phase
		java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER

**Comment by Maciej916** [comment]
Fixed [https://www.curseforge.com/minecraft/mc-mods/maessentials/files/3565169](https://www.curseforge.com/minecraft/mc-mods/maessentials/files/3565169)
